name = "Project Commonwealth"
author = "Alex Ignacio-Gamez"
version = "0.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7c9c82b87474d16c1739407422754e6c0a04f37dd759120ee09f9410895e009"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
