name = "Derpack X"
author = "Alex Ignacio-Gamez"
version = "0.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bdf26c282985752efc8f6a5c0b3f143ce1049434c26343a8f64cfc26045ab95"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
