name = "Derpack X"
author = "Alex Ignacio-Gamez"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8c628d0eebb292804a873c8c6412235dd142de0079621e1660d325b2848d9a1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
