#!/usr/bin/env python3
"""Recipe-graph connectivity metric for Derpack X.

North star (CLAUDE.md): if you drew a line from every item to what it's used for, the pack should look
like ONE or two cohesive webs, not many disconnected clusters. This measures that, four ways — connected
components, distance-to-spine, fragile joints (cut vertices), and material unification — over the mod-jar
recipe digests + our live kubejs/ overlay. Full math in docs/CONNECTIVITY.md.

By default vanilla `minecraft:` is filtered out (it glues everything; see docs). Generalise that with
`--remove`: e.g. `--remove minecraft,create` to see how Create's ADDONS weave once the Create spine and
vanilla are pulled out.

Flags:  --with-vanilla     keep minecraft: nodes
        --jars-only        ignore the kubejs overlay (untouched base game)
        --remove a,b,c     also drop these namespaces (implies vanilla unless --with-vanilla)
"""
import sys, os
from collections import defaultdict
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import recipe_graph_lib as L

WITH_VANILLA = '--with-vanilla' in sys.argv
JARS_ONLY    = '--jars-only' in sys.argv
remove = set()
for i, a in enumerate(sys.argv):
    if a == '--remove' and i + 1 < len(sys.argv):
        remove |= {x.strip() for x in sys.argv[i + 1].split(',') if x.strip()}
if not WITH_VANILLA:
    remove.add('minecraft')

bucket = L.bucket

def main():
    g = L.build(remove=frozenset(remove), overlay=not JARS_ONLY)
    comps = g.components()
    giant = comps[0]
    ni = lambda c: len(g.items_only(c))
    items = sum(ni(c) for c in comps)
    off = items - ni(giant)
    lens = "WITH vanilla" if WITH_VANILLA else "NO vanilla"
    print("# Recipe-graph connectivity\n")
    print(f"_Generated by `tools/recipe-graph/recipe-graph.py` — lens: **{lens}**"
          + (f", removed: `{','.join(sorted(remove))}`" if remove else "")
          + (", base game (jars only)" if JARS_ONLY else ", jars + live kubejs overlay") + "._\n")
    print(f"- item nodes: **{items}**  (+{len(g.nodes)-items} `c:` tags)")
    print(f"- connected components: **{len(comps)}**")
    print(f"- giant component (\"the web\"): **{ni(giant)}** items — {100*ni(giant)//items}% of items")
    print(f"- items OUTSIDE the web: **{off}** across {len(comps)-1} clusters\n")

    # --- blind-spot #2: distance to the Create spine ---
    dist = g.distance_to_spine()
    if dist:
        hist = defaultdict(int)
        for n, d in dist.items():
            if not n.startswith('c:'): hist[d] += 1
        reach = sum(hist.values())
        unreach = items - reach
        avg = sum(d * c for d, c in hist.items()) / max(reach, 1)
        print("## Depth — hops from the Create spine\n")
        print(f"reachable from `create:*`: **{reach}** items (avg **{avg:.1f}** hops); "
              f"unreachable: **{unreach}**")
        print("  " + "  ".join(f"{d}:{hist[d]}" for d in sorted(hist) if d <= 8)
              + (" …" if max(hist) > 8 else "") + "\n")

    # --- blind-spot #1: fragile joints, at the mod level (which mod-removals fragment the web) ---
    proj = g.mod_projection(min_weight=2)
    madj = defaultdict(set)
    mnodes = set()
    for (a, b) in proj:
        madj[a].add(b); madj[b].add(a); mnodes |= {a, b}
    cut = L.Graph(mnodes, madj, {}).articulation_points()
    if cut:
        deg = {m: len(madj[m]) for m in cut}
        top = sorted(cut, key=lambda m: -deg[m])[:14]
        print("## Load-bearing mods (cut vertices — removing one splits the mod web)\n")
        print("  " + ", ".join(f"`{m}`({deg[m]})" for m in top) + "\n")

    # --- islands by mod ---
    by_mod = defaultdict(int); isl = defaultdict(int); big = defaultdict(int)
    for c in comps[1:]:
        cm = defaultdict(int)
        for x in c:
            if not x.startswith('c:'): cm[modof_(x)] += 1
        for m, n in cm.items(): by_mod[m] += n
        if cm:
            d = max(cm, key=cm.get); isl[d] += 1; big[d] = max(big[d], len(c))
    print("## Separate webs / islands by mod\n")
    print("| items off-web | clusters | biggest | bucket | mod |")
    print("|--:|--:|--:|---|---|")
    for m, n in sorted(by_mod.items(), key=lambda x: -x[1]):
        if n >= 5:
            print(f"| {n} | {isl.get(m,0)} | {big.get(m,0)} | {bucket(m)} | `{m}` |")

modof_ = L.modof
if __name__ == '__main__':
    main()
