#!/usr/bin/env python3
"""Regenerate docs/WEAVE-REVIEW.md from the weave corpus + the review data files.

This integrates the pre-1.0 mod-review sweep (docs/MOD-REVIEW.md) with the weave
ledger's candidate corpus, and is RE-RUNNABLE: as more convergence passes land
(targeting ~50), re-run this and the doc refreshes with the latest CANDIDATES.md.

Inputs (all in this dir unless noted):
  phase2/CANDIDATES.md   — the master candidate accumulator (regenerated each pass)
  review-map.json        — modid -> {slug, milestone}; the schedule mapping
  review-dx.json         — modid -> my DX note (hand-maintained; persists across passes)
  review-preamble.md     — static intro (thunderdome framing, synthesis); hand-maintained

Output:
  ../../docs/WEAVE-REVIEW.md

Triage safety: any mod present in CANDIDATES.md (at the threshold) but MISSING from
review-map or review-dx is surfaced in a "Needs triage" section rather than dropped,
so new mods from later passes can't slip through unreviewed.

Usage:  python3 tools/weave-ledger/gen-weave-review.py [--threshold N] [--per-mod K]
"""
import json, re, os, argparse, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
CAND = os.path.join(HERE, "phase2", "CANDIDATES.md")
MAP  = os.path.join(HERE, "review-map.json")
DX   = os.path.join(HERE, "review-dx.json")
PRE  = os.path.join(HERE, "review-preamble.md")
OUT  = os.path.join(ROOT, "docs", "WEAVE-REVIEW.md")

MS = {11:'v0.7.0 — Create spine',12:'v0.8.0 — Stabilization I',13:'v0.9.0 — Economy & logistics',
 14:'v0.10.0 — Stabilization II',15:'v0.11.0 — Magic',16:'v0.12.0 — Stabilization III',
 17:'v0.13.0 — Survival',18:'v0.14.0 — Stabilization IV',19:'v0.15.0 — Polish & site',
 20:'v1.0.0 — Release'}

def parse_candidates(path):
    rows=[]; unique=None
    for line in open(path):
        m=re.match(r'\*\*(\d+) unique', line.strip())
        if m: unique=int(m.group(1))
        if not line.startswith('| '): continue
        c=[x.strip() for x in line.strip().strip('|').split('|')]
        if len(c)<8 or c[0]=='times' or c[0].startswith('--'): continue
        try: t=int(c[0])
        except: continue
        rows.append(dict(times=t, mod=c[2].strip('`'), frm=c[3], via=c[4],
                         pillar=c[5], motif=c[6], consensus=c[7]))
    return rows, unique

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--threshold', type=int, default=2, help='min passes (times) to include')
    ap.add_argument('--per-mod', type=int, default=6, help='max ACCEPT rows shown per mod')
    a=ap.parse_args()

    rows, unique = parse_candidates(CAND)
    rmap=json.load(open(MAP)); dx=json.load(open(DX))
    pre=open(PRE).read() if os.path.exists(PRE) else ""

    ge=[r for r in rows if r['times']>=a.threshold]
    bymod={}
    for r in ge: bymod.setdefault(r['mod'],[]).append(r)

    # group mods by milestone (0 = unmapped/needs triage)
    msmods={}
    triage_map=[]; triage_dx=[]
    for mid in bymod:
        ms = rmap.get(mid,{}).get('milestone', 0)
        msmods.setdefault(ms,[]).append(mid)
        if mid not in rmap: triage_map.append(mid)
        if mid not in dx:   triage_dx.append(mid)

    out=[]
    out.append(pre.rstrip()+"\n" if pre else "# Mod review × weave ledger — integrated analysis\n")
    out.append("> **Generated by `tools/weave-ledger/gen-weave-review.py` — re-run after each pass.** "
        "Edit DX notes in `review-dx.json`, the schedule map in `review-map.json`, and the framing in "
        "`review-preamble.md`; never hand-edit this file.\n")
    out.append("_Last generated: %s · corpus: **%s unique candidates**, showing the **%d** seen in "
        "≥%d passes (the consensus signal)._\n" % (datetime.date.today().isoformat(),
        unique if unique else "?", len(ge), a.threshold))

    if triage_map or triage_dx:
        out.append("\n> ⚠ **Needs triage** (new since the review data was last updated): " +
            (("**unmapped** (add to `review-map.json`): "+", ".join(f"`{m}`" for m in sorted(triage_map))+". ") if triage_map else "") +
            (("**no DX note** (add to `review-dx.json`): "+", ".join(f"`{m}`" for m in sorted(triage_dx))+".") if triage_dx else ""))

    for ms in sorted(MS)+([0] if 0 in msmods else []):
        mids=sorted(msmods.get(ms,[]))
        if not mids: continue
        title = MS.get(ms, "Unmapped — needs triage")
        out.append("\n## %s — %d mods\n" % (title, len(mids)))
        for mid in mids:
            cs=sorted(bymod[mid], key=lambda r:-r['times'])
            acc=[c for c in cs if 'ACCEPT' in c['consensus'].upper()]
            rej=[c for c in cs if 'REJECT' in c['consensus'].upper()]
            motifs=sorted({c['motif'] for c in acc if c['motif'] and c['motif']!='—'})
            slug=rmap.get(mid,{}).get('slug','?')
            out.append("### `%s`  (%s) — %dA / %dR · motifs: %s" %
                (mid, slug, len(acc), len(rej), ", ".join(motifs) or "—"))
            note=dx.get(mid)
            out.append("**DX:** %s" % (note if note else "_no DX note yet — add to `review-dx.json`._"))
            for c in acc[:a.per_mod]:
                out.append("- `%s` ×%d → %s · %s · *via* %s" %
                    (c['motif'], c['times'], c['pillar'], c['frm'][:75], c['via'][:55]))
            out.append("")

    open(OUT,"w").write("\n".join(out)+"\n")
    print("wrote", OUT)
    print("mods: %d  shown candidates: %d  unmapped: %d  missing-DX: %d" %
        (len(bymod), len(ge), len(triage_map), len(triage_dx)))

if __name__=="__main__":
    main()
