#!/usr/bin/env python3
"""Scaffold per-mod weave dossiers from the mod-data digest (Phase 0/1 of docs/WEAVING-PLAN.md).

One `tools/mod-data/dossiers/<namespace>.md` per mod, pre-filled with the JAR-GROUNDED facts so the
Phase-1 web sweep only fills judgment fields and can't silently invent contents. Crucially it fills the
METHODS block — the recipe-*types* a mod registers (read straight from the recipes-digest 2nd column) —
because "weave material X THROUGH mod Y's method" is the core of the plan (WEAVING-PLAN.md §2.0).

Also emits `tools/weave-ledger/methods-palette.md`: the pack-wide catalogue of connective mechanics,
filtered to INSTALLED namespaces (drops dead compat for uninstalled mods like mekanism/IE-only recipes).

Pure stdlib. Re-run after scripts/extract-mod-data.sh on every #161 update. Idempotent for the auto
sections; it PRESERVES hand/sweep-filled judgment fields (see --force to overwrite).

Usage:
  python3 scripts/build-dossiers.py            # generate skeletons + palette (skip already-swept fields)
  python3 scripts/build-dossiers.py --force     # rebuild skeletons from scratch (discards sweep edits!)
"""
import os, re, sys, glob
from collections import defaultdict, Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BYMOD = os.path.join(ROOT, 'tools', 'mod-data', 'by-mod')
RECIPES = os.path.join(ROOT, 'tools', 'mod-data', 'recipes')
LOOT = os.path.join(ROOT, 'tools', 'mod-data', 'loot')
OUT = os.path.join(ROOT, 'tools', 'mod-data', 'dossiers')
PALETTE = os.path.join(ROOT, 'tools', 'weave-ledger', 'methods-palette.md')

FORCE = '--force' in sys.argv

MODID_RE = re.compile(r'modId\s*=\s*"([^"]+)"')
LOADER_NS = {'neoforge', 'forge', 'fabric', 'minecraft', 'mixinextras', 'kffmod'}
# Mods CUT from the pack (no manifest) but still lingering in the instance/digest — see #131 drift.
# Skipped here so the generator doesn't (re)create dossiers / palette rows for them. Manifest-confirmed.
# NOTE: the digest is additive and never deletes uninstalled mods, so this list (not the digest) is the
# authority on what's cut. It is NOT exhaustive of the ~100 stale digest entries (most of those are
# version-drift of INSTALLED mods, which must NOT be cut) — the durable fix is the on-box digest regen
# (#131). Only mods confirmed absent from mods/*.pw.toml belong here.
CUT_NS = {'emi', 'emi_loot', 'emi_ores', 'emiprofessions', 'emi_letsdo_compat',
          'arphex', 'creeperoverhaul', 'mutantmonsters', 'sophisticatedcore',
          # v0.6.0 removals (branch→main delta): SoL family retired for Diet-AppleSeed, libs + content cut
          'bosses_of_mass_destruction', 'cerbons_api', 'coroutil', 'midnightlib', 'mmlib',
          'titanium', 'umapyoi', 'foodvariations', 'solonion', 'solclassic'}
# Marks the auto-generated tail; everything below it is regenerated, everything above is preserved.
AUTO_MARK = '<!-- AUTO-DIGEST-FACTS — regenerated by scripts/build-dossiers.py; edit above this line -->'


def parse_bymod(path):
    """Return dict(jar, modids[], blocks[], items[], tags[], biomes[], primary_ns)."""
    section = None
    d = dict(jar=os.path.basename(path)[:-4], modids=[], blocks=[], items=[], tags=[], biomes=[])
    for line in open(path, encoding='utf-8'):
        s = line.rstrip('\n')
        if s.startswith('## '):
            h = s[3:]
            section = ('meta' if h.startswith('mod metadata') else 'blocks' if h == 'blocks'
                       else 'items' if h == 'items' else 'biomes' if 'biome_modifiers' in h
                       else 'tags' if h.startswith('c:') else None)
            continue
        if not s.strip():
            continue
        if section == 'meta':
            m = MODID_RE.search(s)
            if m:
                d['modids'].append(m.group(1))
        elif section == 'blocks':
            d['blocks'].append(s.strip())
        elif section == 'items':
            d['items'].append(s.strip())
        elif section == 'biomes':
            d['biomes'].append(s.split(' :: ', 1)[0].strip())
        elif section == 'tags':
            d['tags'].append(s.split(' :: ', 1)[0].strip())
    # primary namespace = dominant CONTENT prefix (excluding loader/minecraft, so datapack mods that only
    # ship minecraft:-namespaced content key off their real modId instead of all colliding on "minecraft").
    ns = Counter(x.split(':', 1)[0] for x in d['blocks'] + d['items']
                 if ':' in x and x.split(':', 1)[0] not in LOADER_NS)
    real = [m for m in d['modids'] if m not in LOADER_NS]
    if ns:
        d['primary_ns'] = ns.most_common(1)[0][0]
    elif real:
        d['primary_ns'] = real[0]
    else:
        d['primary_ns'] = (d['modids'][0] if d['modids'] else d['jar'].lower())
    return d


def parse_recipe_types():
    """Return (registered: ns->set(types), made_by: jar->set(foreign types))."""
    registered = defaultdict(set)
    made_by = defaultdict(set)
    for f in glob.glob(os.path.join(RECIPES, '*.txt')):
        jar = os.path.basename(f)[:-4]
        for line in open(f, encoding='utf-8'):
            p = line.rstrip('\n').split(' | ')
            if len(p) < 2:
                continue
            rtype = p[1].strip()
            if ':' not in rtype:
                continue
            ns = rtype.split(':', 1)[0]
            registered[ns].add(rtype)            # type X:y is registered by mod X
            made_by[jar].add(rtype)
    return registered, made_by


def sig_items(items):
    """Pick a grounded sample of representative items: drop blockstate variants (a:b/c), cap the list."""
    base = [i for i in items if '/' not in i.split(':', 1)[-1]]
    return base[:16], len(items)


def material_tags(tags):
    keep = [t for t in tags if re.search(r'(ingots|plates|nuggets|gems|raw_materials|ores|dusts|sheets|'
                                         r'rods|wires|storage_blocks|crops|foods|fruits|seeds)/', t)]
    return keep[:24]


def skeleton(d, registered, made_by, has_loot):
    ns = d['primary_ns']
    sig, nitems = sig_items(d['items'])
    reg = sorted(registered.get(ns, []))
    foreign = sorted(t for t in made_by.get(d['jar'], set()) if t.split(':', 1)[0] != ns
                     and not t.startswith('minecraft:'))
    mats = material_tags(d['tags'])
    deps = [m for m in d['modids'][1:] if m not in LOADER_NS]
    extra_ns = sorted({x.split(':', 1)[0] for x in d['blocks'] + d['items'] if ':' in x} - {ns})

    L = []
    L.append(f'# {ns} — dossier')
    L.append('')
    L.append('<!-- SWEEP: fill the fields marked TODO from a per-mod web sweep (Modrinth/CF/wiki).')
    L.append('     Every content claim must trace to a digest line (below the AUTO mark) or a source URL.')
    L.append('     If the web yields nothing reliable, leave TODO and set status: UNVERIFIED. -->')
    L.append('')
    L.append('one-line:   TODO  — what it is / does, in one sentence')
    L.append('vibe:       TODO  — theme/aesthetic (e.g. arcane-scholarly, rustic-agrarian, industrial)')
    L.append('signature:  TODO  — the 3-6 items/blocks a player actually cares about (pick from facts below)')
    L.append('')
    L.append('methods (FIRST-CLASS — what this mod can DO; the resources other mods pull THROUGH — §2.0):')
    L.append('  registered recipe-types (AUTO, jar-grounded): '
             + (', '.join(reg) if reg else '(none registered)'))
    L.append('  non-recipe mechanics (SWEEP): TODO  — auras, on-kill effects, growth/processing, multiblock'
             ' actions, spell/ritual behaviors not expressed as a recipe type')
    L.append('  consumes / outputs (SWEEP): TODO  — what foreign material its methods could ACCEPT or FEED'
             ' (the join key for opportunity-finding, §6)')
    L.append('')
    L.append('anchors:    TODO (?)  — which loop system(s) it ALREADY feeds (production: create/magic · '
             'pressure: survival · economy incl. logistics/aeronautics; see docs/SYSTEMS.md). '
             'Count = current anchor tally.')
    L.append('2nd-anchor candidates (SWEEP — PREFER method-routings; cite a motif M-01..M-24 where one fits):')
    L.append('  - TODO: <loop system> via <through which method> — <hook>   [STRONG/MED/WEAK]')
    L.append('  - (if none is coherent, write "none — leave"; do NOT force an edge)')
    L.append('')
    L.append('how-packs-integrate (SWEEP): TODO  — how curated packs commonly wire this mod (with URL)')
    L.append('sources (SWEEP): TODO  — [modrinth/cf url] [wiki url]')
    L.append('status:     UNVERIFIED (skeleton)   — set to VERIFIED once the SWEEP fields are filled + sourced')
    L.append('')
    L.append(AUTO_MARK)
    L.append('')
    L.append(f'jar:            {d["jar"]}')
    L.append(f'primary ns:     {ns}' + (f'   (also ships: {", ".join(extra_ns)})' if extra_ns else ''))
    L.append(f'deps:           {", ".join(deps) if deps else "(none beyond loader)"}')
    L.append(f'counts:         {len(d["blocks"])} blocks, {nitems} items, '
             f'{len(d["biomes"])} biome-modifiers, {len(d["tags"])} c:tags, loot={"yes" if has_loot else "no"}')
    L.append(f'made-by methods (foreign types this mod\'s recipes USE — existing inbound weaves): '
             + (', '.join(foreign) if foreign else '(none / vanilla only)'))
    L.append(f'material c:tags: {", ".join(mats) if mats else "(none)"}')
    L.append('blocks (grounded): ' + (', '.join(d['blocks'][:40]) + (' …' if len(d['blocks']) > 40 else '')
                                       if d['blocks'] else '(none)'))
    L.append('item sample (grounded): ' + (', '.join(sig) + (' …' if nitems > len(sig) else '')))
    L.append('')
    return '\n'.join(L)


def merge(existing, fresh):
    """Preserve everything above the AUTO mark in `existing`; replace the AUTO tail with `fresh`'s tail."""
    if FORCE or AUTO_MARK not in existing:
        return fresh
    head = existing.split(AUTO_MARK, 1)[0]
    tail = fresh.split(AUTO_MARK, 1)[1]
    return head + AUTO_MARK + tail


def main():
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(os.path.dirname(PALETTE), exist_ok=True)
    registered, made_by = parse_recipe_types()
    loot_jars = {os.path.basename(f)[:-4] for f in glob.glob(os.path.join(LOOT, '*.txt'))}

    mods = [parse_bymod(f) for f in sorted(glob.glob(os.path.join(BYMOD, '*.txt')))]
    installed = {m['primary_ns'] for m in mods} | {x.split(':', 1)[0]
                                                    for m in mods for x in m['blocks'] + m['items'] if ':' in x}

    seen, written, preserved = {}, 0, 0
    for d in mods:
        ns = d['primary_ns']
        if ns in CUT_NS:
            continue   # cut from the pack — don't generate a dossier (see #131 drift)
        key = ns if ns not in seen else f'{ns}__{d["jar"][:12]}'
        seen[ns] = seen.get(ns, 0) + 1
        path = os.path.join(OUT, f'{key}.md')
        fresh = skeleton(d, registered, made_by, d['jar'] in loot_jars)
        if os.path.exists(path):
            out = merge(open(path, encoding='utf-8').read(), fresh)
            if AUTO_MARK in open(path, encoding='utf-8').read() and not FORCE:
                preserved += 1
        else:
            out = fresh
        open(path, 'w', encoding='utf-8').write(out)
        written += 1

    # ---- methods palette: installed namespaces only, sorted by method count ----
    live = {ns: sorted(ts) for ns, ts in registered.items()
            if ns in installed and ns not in LOADER_NS and ns not in CUT_NS}   # drop vanilla/loader/cut
    rows = sorted(live.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    P = ['# Methods palette — the pack-wide catalogue of connective mechanics',
         '',
         '> AUTO-GENERATED by `scripts/build-dossiers.py` (union of installed mods\' registered recipe-types).',
         '> This is the shopping list for weaving: to give a mod a 2nd anchor, route one of its materials',
         '> THROUGH one of these methods (WEAVING-PLAN.md §2.0/§6). Dead compat for uninstalled mods is dropped.',
         '',
         f'**{sum(len(v) for v in live.values())} methods across {len(live)} installed mods.**',
         '',
         '| mod (namespace) | # | registered methods (recipe-types) |',
         '|---|--:|---|']
    for ns, ts in rows:
        P.append(f'| `{ns}` | {len(ts)} | {", ".join("`"+t+"`" for t in ts)} |')
    open(PALETTE, 'w', encoding='utf-8').write('\n'.join(P) + '\n')

    print(f'dossiers: {written} written ({preserved} had sweep-content preserved) -> {OUT}')
    print(f'palette:  {sum(len(v) for v in live.values())} methods / {len(live)} mods -> {PALETTE}')


if __name__ == '__main__':
    main()
