#!/usr/bin/env python3
"""Recipe-graph connectivity metric for Derpack X.

Design north star (CLAUDE.md): if you drew a line from every item to what it's used
for, the result should be ONE or two cohesive webs — not many disconnected clusters.
This script measures that directly. It reads the recipe digests in
tools/mod-data/recipes/*.txt (format: `recipe_id | type | <space-separated tokens>`),
builds an undirected graph where the nodes are real items + `c:` tags and every recipe
unions all of its tokens together, then reports the connected components.

The giant component is "the web". Everything else is an island — a cluster whose items
only craft among themselves and never link to the spine. Islands are the worklist:
each one needs ~one bridge recipe to rejoin the web (NOT a gate on every variant).

Usage:  python3 tools/recipe-graph.py [recipes_dir]   # prints a markdown report
"""
import re, sys, glob, os
from collections import defaultdict

RECIPE_DIR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), 'mod-data', 'recipes')

# Tokens in field 3 that are NOT items/tags: recipe-type ids, mod-loaded conditions, feature flags.
_RTYPE = re.compile(r'[a-z_0-9]+:(crafting_shaped|crafting_shapeless|smelting|blasting|smoking|'
                    r'campfire_cooking|stonecutting|smithing_transform|smithing_trim|pressing|mixing|'
                    r'crushing|cutting|milling|compacting|deploying|filling|emptying|haunting|splashing|'
                    r'sandpaper_polishing|sequenced_assembly|mechanical_crafting|item_application)$')
def _noise(tok):
    return (':' not in tok
            or tok.endswith(':flag') or 'feature_item_enabled' in tok
            or re.match(r'(fabric|neoforge|forge):(mod_loaded|not|or|and|always|never|true|false)', tok)
            or _RTYPE.match(tok))

modof = lambda t: t.split(':', 1)[0]

# Rough buckets for the top island mods, so the report is actionable rather than just a dump.
# (Interpretation only — the graph itself is mod-agnostic.)
BUCKET = {
    'block/deco':  {'more_slabs_stairs_and_walls','upgrade_aquatic','quark','mcwroofs','galosphere',
                    'domum_ornamentum','usefulfoundation','undergroundworlds','biomeswevegone','dynamictrees'},
    'tech/gear':   {'createnuclear','createbigcannons','cbc_at','northstar','create_d2d','tfmg',
                    'create_ironworks','createaddition','dndesires','thermal','silentgear','minecolonies'},
    'organic/mob': {'alexsmobs','naturalist','vinery','tide','ecologics','deeperdarker','cataclysm',
                    'mutantmonsters','beachparty','snowyspirit','grimoireofgaia','deep_aether',
                    'eternal_starlight','born_in_chaos_v1','farm_and_charm'},
    'magic':       {'ars_nouveau','forbidden_arcanus'},
    'security':    {'securitycraft'},
    'misc/util':   {'simplehats','extradelight','supplementaries','snowyspirit'},
    'phantom':     {'recipe_integration','spawn','minecraft'},   # compat/uninstalled/tag artifacts
}
def bucket(m):
    for b, ms in BUCKET.items():
        if m in ms: return b
    return 'other'

def build():
    nodes, edges = set(), []
    for f in glob.glob(os.path.join(RECIPE_DIR, '*.txt')):
        for line in open(f, encoding='utf-8'):
            p = line.rstrip('\n').split(' | ')
            if len(p) < 3: continue
            toks = list(dict.fromkeys(t for t in p[2].split() if not _noise(t)))
            for n in toks: nodes.add(n)
            for b in toks[1:]:
                edges.append((toks[0], b))
    parent = {n: n for n in nodes}
    def find(x):
        r = x
        while parent[r] != r: r = parent[r]
        while parent[x] != r: parent[x], x = r, parent[x]
        return r
    for a, b in edges:
        ra, rb = find(a), find(b)
        if ra != rb: parent[ra] = rb
    comps = defaultdict(set)
    for n in nodes: comps[find(n)].add(n)
    return nodes, sorted(comps.values(), key=len, reverse=True)

def main():
    nodes, comps = build()
    giant = comps[0]
    items = [n for n in nodes if not n.startswith('c:')]
    out = sum(len(c) - sum(1 for x in c if x.startswith('c:')) for c in comps[1:])
    print(f"# Recipe-graph connectivity\n")
    print(f"_Generated by `tools/recipe-graph.py` from `tools/mod-data/recipes/`._\n")
    print(f"- nodes: **{len(nodes)}** (items {len(items)}, `c:` tags {len(nodes)-len(items)})")
    print(f"- connected components: **{len(comps)}**")
    print(f"- giant component (\"the web\"): **{len(giant)}** — {100*len(giant)//len(nodes)}% of all nodes")
    print(f"- item-nodes OUTSIDE the web (islands): **{out}** across {len(comps)-1} clusters\n")

    by_mod = defaultdict(int); by_mod_isl = defaultdict(int)
    for c in comps[1:]:
        cm = defaultdict(int)
        for x in c:
            if not x.startswith('c:'): cm[modof(x)] += 1
        for m, n in cm.items(): by_mod[m] += n
        if cm: by_mod_isl[max(cm, key=cm.get)] += 1

    print("## Islands by mod\n")
    print("| items off-web | islands | bucket | mod |")
    print("|--:|--:|---|---|")
    for m, n in sorted(by_mod.items(), key=lambda x: -x[1]):
        if n >= 4:
            print(f"| {n} | {by_mod_isl.get(m,0)} | {bucket(m)} | `{m}` |")

if __name__ == '__main__':
    main()
